language: node_js
before_script:
  # - npm install -g gulp
  - node_modules/.bin/bower install
script:
  - node_modules/.bin/gulp
  # temporary fix for building both versions before running gulp test
  - NODE_ENV=1 node_modules/.bin/gulp build
  - node_modules/.bin/gulp test
